import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClerkMigrationTool from "./_auth-migration/clientMigrationWrapper";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      {/* <ClerkMigrationTool url={"/api/clerk-migrate"}> */}
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
      {/* </ClerkMigrationTool> */}
    </ClerkProvider>
  );
}
